---
- name: Install Nginx
  apt:
    name: nginx
    state: latest
  register: nginxinstalled
  notify:
    - nginx start

- name: Add Nginx cofig
  when: nginxinstalled is success
  template: 
    src: default.j2
    dest: "/etc/nginx/sites-available/default"
    owner: www-data
    group: www-data
  notify:
    - nginx restart

