---
- name: Run apt update
  become: yes
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 86400 #one day
  
- name: Install needed packages
  become: yes
  apt:  
    pkg:
      - acl
      - python3-pip
      - python3-dev
      - python3-virtualenv
      - libpq-dev
      - postgresql-13
      - postgresql-contrib
      - python3-psycopg2
      - curl
    state: latest

