---
- name: Start postgres
  service: name=postgresql enabled=yes state=started

- name: Create database
  postgresql_db: name={{ db_name }}
                 encoding=UTF-8
  become: yes
  become_user: postgres

- name: Create user
  no_log: yes
  postgresql_user: db={{ db_name }}
                   name={{ db_user }}
                   password={{ db_password }}
                   priv=ALL
                   state=present
                   role_attr_flags=NOSUPERUSER,NOCREATEDB
  become: yes
  become_user: postgres

